language: go

go:
  - 1.12.x
  - 1.11.x
  
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

before_script:
  - bash ./travis-before-script.sh

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - golangci-lint run
  - go test ./...
